/*
 * Created on 2022-11-15 ( Time 13:29:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */



import express from 'express';
import { body } from 'express-validator';
import { inject, injectable } from 'inversify';
import { jwtValidator } from '../authentication/jwt-validator';
import { IProfileController } from '../controllers/interfaces/profile.controller.interface';
import { EdiMessage } from '../models/edi-message.model';
import { loggable } from '../utils/logger.util';
import { ModelUtil } from '../utils/model.util';
import { Symbols } from '../utils/types';
import { CustomRouter } from './interfaces/custom-router.interface';

@injectable()
export class BulletinBoardRouter implements CustomRouter {
    public path = '/profile';
    public router = express.Router();

    constructor(@inject(Symbols.IProfileController) private controller: IProfileController) {
        this.initializeRoutes();
    }

    @loggable()
    private initializeRoutes(): void {

        // this.router.get('/', [jwtValidator], this.controller.getProfileDetails.bind(this.controller));

        this.router.post('/', [jwtValidator], this.controller.getProfileDetails.bind(this.controller));
    }

}
