/*
 * Created on 2022-12-12 ( Time 09:49:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */


import { injectable } from 'inversify';
import { EdiMessage } from '../models/edi-message.model';
import { MirEdiCntntTbl } from '../models/miredicntnttbl.model';


/**
 * Translator Service
 */
@injectable()
export class TranslatorService {

    public static translateToMirEdiCntntTbl( ediMessage: EdiMessage ) {
        const result: MirEdiCntntTbl = new MirEdiCntntTbl();
        const app = ediMessage.application ??= "";
        result.ediCntntTopcTxt = translateToTopcTxt( app);
        result.ediCntntTxt = ediMessage.message ??= "";
        result.ediCntntAuthedDt = (new Date()).toISOString();
        return result;
    }

    public static translateToEdiMessage( mirEdiCntntTbl: any ) {
        const result: EdiMessage = new EdiMessage();
        const topicTxt = mirEdiCntntTbl.ediCntntTopcTxt ??= "";
        result.application = translateToApplication(topicTxt);
        result.message = mirEdiCntntTbl.ediCntntTxt ??= "";
        return result;
    }

}

/**
 */
function translateToTopcTxt(application: string): string {
    switch (application) {
        case 'ECRS':
            return 'ECSTOPIC'

        case 'CRCP':
            return 'GHPTOPIC'

        case 'MSPRP':
            return 'MRPTOPIC'

        case 'WCMSAP':
            return 'WCSTOPIC'
        
        case 'Section 111':
            return 'MRATOPIC'

        default:
            break;
    }

    return '';
}

function translateToApplication(ediCntntTopcTxt: string): string {
    switch (ediCntntTopcTxt) {
        case 'ECSTOPIC':
            return 'ECRS'

        case 'GHPTOPIC':
            return 'CRCP'

        case 'MRPTOPIC':
            return 'MSPRP'

        case 'WCSTOPIC':
            return 'WCMSAP'
        
        case 'MRATOPIC':
            return 'Section 111'
        default:
            break;
    }

    return '';
}

