/*
 * Created on 2022-11-15 ( Time 13:29:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { NextFunction, Request, Response } from 'express';

export interface IAuthenticationController {

	login(req: Request, res: Response, next: NextFunction): void;

	logout(req: Request, res: Response, next: NextFunction): void;

	refresh(req: Request, res: Response, next: NextFunction): void;

}
