/*
 * Created on 2022-11-15 ( Time 13:29:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { NextFunction, Request, Response } from 'express';

export interface IBulletinBoardController {

	updateBulletinBoardMessages(req: Request, res: Response, next: NextFunction): any;

	getLatestBulletinBoardMessages(req: Request, res: Response, next: NextFunction): void;

}
