/*
 * Created on 2022-12-08 ( Time 11:29:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
import { describe, expect, test, beforeEach } from '@jest/globals';
import { createResponse, createRequest } from 'node-mocks-http';
import 'reflect-metadata';


import { Symbols } from '../../src/utils/types';
import { setSuccessResponse, setErrorResponse } from '../../src/utils/ediresponse.util';

const paramsRequest = createRequest({ params: { sectId: 1 } });
const response = createResponse(); 

describe('Test setSuccessResponse ', () => {

    // let serviceMock: CobAcntActvtyServiceMock;

    beforeEach(() => {
        // serviceMock = new CobAcntActvtyServiceMock();
    });

    test('success should set status 200', () => {

        setSuccessResponse( "this is a test", response);

        expect(response.statusCode).toEqual(200);
    });

    test('success should set status 201', () => {

        setSuccessResponse( "this is a test", response, 201);

        expect(response.statusCode).toEqual(201);
    });

    test('error should set status 401', () => {

        setErrorResponse( response, "did something wrong", 401);

        expect(response.statusCode).toEqual(401);
    });
    
});



