/*
 * Created on 2022-12-08 ( Time 13:18:11 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
import { describe, expect, test, beforeEach } from '@jest/globals';
import { Container } from 'inversify';
import 'reflect-metadata';
import { AuthenticationService } from '../../src/services/authentication-service';
import { IAuthenticationService } from '../../src/services/interfaces/authentication-service.interface';
import { User } from '../../src/types/custom';
import { Symbols } from '../../src/utils/types';



describe('Test Authentication Service', () => {

    let container: Container;
    let service: AuthenticationService;
    const testRecord = [ {application: 'test', message:'test message' }, {application:'test', message:''}];

    beforeEach(() => {
        container = new Container();
        container.bind<IAuthenticationService>(Symbols.IAuthenticationService).to(AuthenticationService);

        service = container.resolve(AuthenticationService);

    });

    test('Service should initialize successfully', () => {
        expect(service).toBeDefined();
    });

    test('Service should authenticate user', async () => {
  
       let result: User = await service.authenticateUser('test', 'test');
       
       expect(service).toBeDefined();
       expect(result).toBeDefined();
       expect(result.name).toBe('test');
        
    });


});

