/*
 * Created on 2022-11-21 ( Time 15:41:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { NextFunction, Request, Response } from 'express';
import { inject, injectable } from 'inversify';
import { EdiMessage } from '../models/edi-message.model';
import { User } from '../types/custom';
import { setErrorResponse, setSuccessResponse } from '../utils/ediresponse.util';
import { loggable } from '../utils/logger.util';
import { Symbols } from '../utils/types';
import { AbstractController } from './abstract-controller';
import { logger } from '../utils/winston.config';
import { IProfileController } from './interfaces/profile.controller.interface';
import { IProfileService } from '../services/interfaces/profile.service.interface';
/**
 * CobAcntActvty Controller
 */
@injectable()
export class ProfileController extends AbstractController implements IProfileController {

     constructor(@inject(Symbols.IProfileController)  private service: IProfileService) {
        super();
    }
    
	/**
     * Get the profile details by email 
     * @param req, res
     * @return exists response's code status and body
     */
    @loggable(false, false)
    public async getProfileDetails(req: Request, res: Response, next: NextFunction): Promise<void> {
        try {
            const messages = await this.service.getProfile();
            setSuccessResponse( messages, res);
            
        } catch (error) {
            logger.error( error);
            setErrorResponse(res, error);
        }
    }

   
}
