/*
 * Created on 2022-11-21 ( Time 15:41:45 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { Response } from 'express';
import { EdiResponse } from '../models/edi-respose.model';

import { logger } from './winston.config';

/**
 * EDIResponse Controller
 */
    export  function setSuccessResponse(value: any, res: Response, status: number = 200 ): void {
        const response: EdiResponse = createEdiResponse( status, value);
        res
            .json(response)
            .status(status);

    }

    export  function setErrorResponse(res: Response, error: any, status: number = 500  ): void {
        const errors: any[] = [];
        errors.push(error);

        const response: EdiResponse = createEdiResponse( status, null, errors);
        logger.error(errors);
        res
            .json(response)
            .status(status);
    }

    export  function createEdiResponse(  status: number, result: any, errors: any[] | undefined = undefined): EdiResponse {
        const response: EdiResponse = new EdiResponse;
        response.status = status;
        response.result = result;
        if( errors ) {
            response.errors = errors;
        }
        response.timestamp = Date.now().toString();
        return response;
    }



