/*
 * Created on 2022-11-15 ( Time 13:29:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

const Symbols = {
    IBulletinBoardService: Symbol.for('IBulletinBoardService'),
    IBulletinBoardController: Symbol.for('IBulletinBoardController'),
    IBulletinBoardRepository: Symbol.for('IBulletinBoardRepository'),
    IProfileController: Symbol.for('IProfileController'),
    IProfileRepository:Symbol.for('IProfileRepository'),
    IAuthenticationController: Symbol.for('IAuthenticationController'),
    IAuthenticationService: Symbol.for('IAuthenticationService'),

};

export { Symbols };




