/*
 * Created on 2022-11-15 ( Time 13:29:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { JsonObject } from 'json2typescript';

/**
 * MirEdiCntntTbl Entity (ES6 Class)
 */
@JsonObject('MirEdiCntntTbl')
export class MirEdiCntntTbl {
        public ediCntntId : number = 0;
        public ediRepLoginId : string = '';
        public ediCntntAuthedDt : any = undefined;
        public ediCntntTopcTxt : string = '';
        public ediCntntTxt : string = '';
}
