/*
 * Created on 2022-12-08 ( Time 12:35:11 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { EdiMessage } from "../../models/edi-message.model";
import { User } from "../../types/custom";


export interface IBulletinBoardService {
    getLatestMessages(): Promise<EdiMessage[]>;

    updateMessages( user: User, messages: EdiMessage[]): Promise<void>;
}