/*
 * Created on 2022-12-08 ( Time 12:35:11 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

import { ProfileModel } from "../../models/profile.model";



export interface IProfileService {
    getProfile(): Promise<ProfileModel>;

}